# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:  # We only want to trigger the deployment when master is updated
- master

pr: none  # Preventing this to run on Pull Requests

pool:
  vmImage: 'windows-latest'

variables:
- group: Pomodoro           # Contains azureSubscriptionID
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'

jobs:
- job: Publishing
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Publish the project - Release'
    inputs:
      command: 'publish'      # This will also build the project
      projects: '**/*.csproj'
      publishWebProjects: false
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/Release'
      zipAfterPublish: true
  - publish: '$(Build.ArtifactStagingDirectory)'
    artifact: 'WebbApp'
- job: Deploying
  dependsOn: Publishing
  condition: succeeded()
  steps:
  - download: current
    artifact: 'WebbApp'
  - task: AzureWebApp@1
    inputs:
      azureSubscription: '$(azureSubscriptionID)'
      appName: 'sienpomodoro'
      package: $(Pipeline.Workspace)/**/*.zip  

